import { Metadata } from "next";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Breadcrumb } from "@/components/Breadcrumb";
import { Navigation } from "@/components/Navigation";

export const metadata: Metadata = {
  title: "OTP Export Conversion Guide | OTP Bridge",
  description:
    "Step-by-step guide to convert Google Authenticator exports into standard TOTP QR codes for compatible authenticator apps.",
  keywords:
    "otp export conversion, google authenticator export, totp qr codes, authenticator compatibility",
};

const steps = [
  {
    number: 1,
    title: "Prepare Google Authenticator",
    description: "Open Google Authenticator on your current device",
    details: [
      "Ensure you have access to your current Google Authenticator app",
      "Have your new device or target authenticator app ready",
    ],
  },
  {
    number: 2,
    title: "Export from Google Authenticator",
    description: "Generate an OTP export QR code",
    details: [
      "Open Google Authenticator app",
      "Use the account transfer option to export accounts",
      "Follow the app's prompts to verify access and select the accounts to export",
    ],
  },
  {
    number: 3,
    title: "Scan with OTP Bridge",
    description: "Convert your OTP export",
    details: [
      "Visit otpbridge.org in your web browser",
      "Choose 'Scan QR Code' or 'Upload Image'",
      "Scan the Google Authenticator QR code or upload a screenshot",
    ],
  },
  {
    number: 4,
    title: "Import to a Compatible Authenticator",
    description: "Add your TOTP accounts",
    details: [
      "OTP Bridge will display all your extracted 2FA accounts",
      "Each account will have its own QR code",
      "Open an authenticator app that supports your account's TOTP settings",
      "Choose to add a new account",
      "Scan each QR code generated by OTP Bridge",
      "Verify that all accounts are imported correctly",
    ],
  },
];

const tips = [
  {
    title: "Convert Each Export",
    description:
      "If your export contains multiple QR codes, convert each one separately.",
  },
  {
    title: "Verify Your Setup",
    description:
      "Check that your imported accounts generate working codes before making any changes to your existing setup.",
  },
];

export default function GuidePage() {
  return (
    <div className="flex flex-col items-center justify-start py-6 px-3 bg-muted min-h-screen">
      <div className="w-full max-w-4xl space-y-8">
        <Breadcrumb items={[{ name: "Home", href: "/" }, { name: "Guide" }]} />
        <h1 className="text-4xl font-bold text-center mb-8">
          OTP Export Conversion Guide
        </h1>
        <p className="text-xl text-muted-foreground text-center mb-12">
          Step-by-step instructions to convert Google Authenticator exports into
          standard TOTP QR codes
        </p>

        <div className="space-y-8 mb-12">
          {steps.map((step, index) => (
            <Card key={index}>
              <CardHeader>
                <div className="flex items-center gap-4">
                  <Badge
                    variant="outline"
                    className="text-lg px-3 py-1 aspect-square"
                  >
                    {step.number}
                  </Badge>
                  <div>
                    <CardTitle className="text-xl">{step.title}</CardTitle>
                    <CardDescription className="text-base">
                      {step.description}
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {step.details.map((detail, i) => (
                    <li key={i} className="flex items-center gap-3">
                      <span className="text-blue-600 ">•</span>
                      <span>{detail}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="mb-8">
          <h2 className="text-2xl font-bold mb-6">
            Tips for Converting OTP Exports
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {tips.map((tip, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="text-lg">{tip.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{tip.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
        <div className="pt-6 border-t border-border w-full">
          <Navigation />
        </div>
      </div>
    </div>
  );
}
