import { Metadata } from "next";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Breadcrumb } from "@/components/Breadcrumb";

export const metadata: Metadata = {
  title: "Complete Guide to 2FA Migration | OTP Bridge",
  description:
    "Step-by-step guide to transfer Google Authenticator codes to any app. Learn how to backup, export, and migrate your 2FA accounts safely.",
  keywords:
    "how to backup google authenticator, transfer 2fa to new phone, google authenticator qr code export, 2fa migration guide",
};

const steps = [
  {
    number: 1,
    title: "Prepare Google Authenticator",
    description: "Open Google Authenticator on your current device",
    details: [
      "Ensure you have access to your current Google Authenticator app",
      "Have your new device or target authenticator app ready",
    ],
  },
  {
    number: 2,
    title: "Export from Google Authenticator",
    description: "Generate migration QR code",
    details: [
      "Open Google Authenticator app",
      "Tap the three dots menu (⋮) in the top right",
      "Select 'Transfer accounts' from the menu",
      "Choose 'Export accounts' (you may need to verify with your device password)",
      "Select the accounts you want to transfer (up to 10 at a time)",
    ],
  },
  {
    number: 3,
    title: "Scan with OTP Bridge",
    description: "Import migration data",
    details: [
      "Visit otpbridge.org in your web browser",
      "Choose 'Scan QR Code' or 'Upload Image'",
      "Scan the Google Authenticator QR code or upload a screenshot",
    ],
  },
  {
    number: 5,
    title: "Import to Target Authenticator",
    description: "Complete the migration",
    details: [
      "OTP Bridge will display all your extracted 2FA accounts",
      "Each account will have its own QR code",
      "Open your preferred authenticator app (Authy, 1Password, etc.)",
      "Choose to add a new account",
      "Scan each QR code generated by OTP Bridge",
      "Verify that all accounts are imported correctly",
    ],
  },
];

const tips = [
  {
    title: "Transfer in Batches",
    description:
      "Google limits transfers to 10 accounts at a time. If you have more, repeat the process.",
  },
  {
    title: "Test codes",
    description:
      "Don't immediately delete Google Authenticator. Test your new setup first.",
  },
];

export default function GuidePage() {
  return (
    <div className="flex flex-col items-center justify-start py-6 px-3 bg-muted min-h-screen">
      <div className="w-full max-w-4xl space-y-8">
        <Breadcrumb items={[{ name: "Home", href: "/" }, { name: "Guide" }]} />
        <h1 className="text-4xl font-bold text-center mb-8">
          Complete Guide to 2FA Migration
        </h1>
        <p className="text-xl text-muted-foreground text-center mb-12">
          Step-by-step instructions to safely transfer your Google Authenticator
          codes
        </p>

        <div className="space-y-8 mb-12">
          {steps.map((step, index) => (
            <Card key={index}>
              <CardHeader>
                <div className="flex items-center gap-4">
                  <Badge variant="outline" className="text-lg px-3 py-1">
                    {step.number}
                  </Badge>
                  <div>
                    <CardTitle className="text-xl">{step.title}</CardTitle>
                    <CardDescription className="text-base">
                      {step.description}
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {step.details.map((detail, i) => (
                    <li key={i} className="flex items-center gap-3">
                      <span className="text-blue-600 ">•</span>
                      <span>{detail}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="mb-8">
          <h2 className="text-2xl font-bold mb-6">
            Pro Tips for Successful Migration
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {tips.map((tip, index) => (
              <Card key={index}>
                <CardHeader>
                  <CardTitle className="text-lg">{tip.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">{tip.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
